import { Icon } from "@/lib/db/schema/icons";
import { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Collection",
  description: "Generated by create next app",
  icons: {
    icon: "/next.svg",
  },
};

export default async function Page() {
  const icons = { data: [] };
  return (
    <main className="container mx-auto mt-24 flex flex-col gap-4 px-8">
      <h1 className="text-4xl">Your Icons</h1>

      <ul className="grid grid-cols-2 gap-4 sm:grid-cols-4 md:grid-cols-6">
        {icons.data?.map((icon: Icon) => (
          <li key={icon.id}>
            <Image
              className="w-full rounded-lg"
              width="100"
              height="100"
              alt={icon.prompt ?? "an image of an icon"}
              src={`https://icon-generator-course.s3.amazonaws.com/${icon.id}`}
            />
          </li>
        ))}
      </ul>
    </main>
  );
}
